import type { Metadata } from "next"
import "./globals.css"
import { satoshi } from "@/assets/font"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={satoshi.variable}>
      <body className={`${satoshi.variable} antialiased`}>{children}</body>
    </html>
  )
}
